plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

//Use the existing Neoforge data generator for resource pack data
def generatedResources = project(":neoforge").file("src/generated/resources")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    //Use the Access Widener File in the Common project module
    def aw = project(':fabric').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

repositories {

    // the repository for Cloth Config
    maven { url = uri("https://maven.shedaniel.me/") }

    maven {
        url = uri("https://cursemaven.com")
    }

    maven {
        name = "TerraformersMC"
        url = uri("https://maven.terraformersmc.com/")
    }

    maven {
        name = "Fuzs Mod Resources"
        url = uri("https://raw.githubusercontent.com/Fuzss/modresources/main/maven/")
    }
	
	maven {
		name = "Ladysnake Libs"
		url = 'https://maven.ladysnake.org/releases'
	}
}

dependencies {

    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
//        parchment("org.parchmentmc.data:parchment-${rootProject.parchment_minecraft_version}:${rootProject.parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    // Fabric API. This is technically optional, but we need this for Forge Config API Port and Cloth Config
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"


    modApi("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    include "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"

    modCompileOnly("com.terraformersmc:modmenu:${rootProject.mod_menu_version}") {
        transitive(false)
    }
    modRuntimeOnly("com.terraformersmc:modmenu:${rootProject.mod_menu_version}")
	
	//Remove Immersive Portals until it is more stable
	
	//Comment out Trinkets integration until it's updated to latest MC version
	//modCompileOnly ("dev.emi:trinkets:${rootProject.trinkets_version}")
}

/* IntelliJ Project Import
 * The Mixin annotation process does not have an obfuscation source when running through the IntelliJ compiler,
 * Thus we have to prevent it from being activated as part of importing this Gradle project into IntelliJ.
 */
if (System.getProperty("idea.sync.active") == "true") {
    afterEvaluate {
        tasks.withType(JavaCompile).all {
            it.options.annotationProcessorPath = files()
        }
    }
}