# Gradle
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

#Project
java_version=21

# Mod Properties
jar_name=tardis_refined
mod_id=tardis_refined
mod_version=2.1.5
maven_group=whocraft.tardis_refined
minecraft_version=1.21.6
archives_base_name=tardis_refined
resource_pack_format=63

# Multiloader Properties

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.6-20250617.151856

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft_version=1.21.5
parchment_version=2025.06.15

enabled_platforms=neoforge,fabric,forge

#Common Mods.toml or Mod.Json Info
mod_name=TARDIS Refined
# Add "," between entries. Don't add quotation marks to the first and last characters.
mod_author=CommandrMoose / River, Jeryn99, Magic Man, ILikePandas, Jacob K, 50ap5ud5
credits=Commoble, Lucraft, starray1000000, Monsterwaill, TheJudge, LoxiGoose
mod_description=TARDIS: Refined is a Minecraft mod based on the world of Doctor Who that adds a personal, teleporting base to the game. The mod explores the nature of the TARDIS and how it operates and expresses its personality.
homepage=https://github.com/Whocraft/TardisRefined
sources=https://github.com/Whocraft/TardisRefined
logo_file=tardis_refined.png
issue_tracker_url=https://github.com/Whocraft/TardisRefined/issues
license=https://github.com/Whocraft/TardisRefined/blob/dev/1.21.x/LICENSE.MD


#Fabric Version Ranges
main_mod_class=whocraft.tardos_refined.fabric.TardisRefinedFabric
mod_menu_integration_class=whocraft.tardis_refined.fabric.compat.ConfigModMenuIntegration

fabric_loader_version=0.16.14
#Fabric API version
##Required for Forge Config API
fabric_api_version=0.127.0+1.21.6
fabric_api_version_range=>=0.127.0+1.21.6
fabric_loader_version_range=>=0.15.11
fabric_minecraft_version_range=>=1.21.6 <=1.22
fabric_java_version_range=>=21
yarn_mappings=1.21.6+build.1

#Neoforge Version Ranges
neoforge_version=21.6.11-beta
neoforge_version_range=[21.6.11-beta,)
neoforge_loader_version_range=[4,)
neoforge_java_version_range=[21,)
neoforge_minecraft_version_range=[1.21.6, 1.22)

#Forge Version Ranges
forge_version=56.0.7
forge_version_range=[56.0.7,)
forge_loader_version_range=[0,)
forge_minecraft_version_range=[1.21.6, 1.22)

# Common Dependencies
forge_config_api_port_version=21.5.1
mixin_version=0.8.5
mixin_extras_version=0.4.1
flywheel_minecraft_version=1.21.6

#Fabric Dependencies only for compile
cloth_config_version=19.0.147
mod_menu_version=15.0.0-beta.3

create_version_fabric = 0.5.1-f-build.1376+mc1.20.1
create_version_plain = 0.5.1.f
flywheel_version_fabric = 0.6.10-2

registrate_version_fabric = 1.3.62-MC1.20.1

#fabric_immersive_portals_version_range=>=2.6.6
#jei_fabric_version=4767571
#trinkets_version=3.8.0
#dev_auth_module_fabric=fabric
#dev_auth_fabric_version=1.1.2

# Fabric Dependencies only for runtime

# Neoforge Dependencies only for compile

# Neoforge Dependencies only for runtime

#Forge Dependencies for compile
valkyrienskies_version=2.3.0-beta.5

#Forge Dependencies only for runtime
world_edit_version=4807512
structure_expansion_version=3909814
jei_version=4473386
immersive_portals_forge_version=4477738
dev_auth_module_forge=forge-latest
dev_auth_forge_version=1.1.2
sodium_version=mc1.21.6-0.6.13

flywheel_version_forge = 0.6.10-8
create_version_forge = 0.5.1.f-26

registrate_version_forge = MC1.20-1.3.11

#Publishing
curseforge_id_forge=782697
curseforge_id_fabric=782697
modrinth_id=nqVt6aES