package whocraft.tardis_refined.client.model.blockentity.console.animations;// Save this class in your mod and generate all required imports

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

/**
 * Made with Blockbench 4.9.4
 * Exported for Minecraft version 1.19 or later with Mojang mappings
 * @author Author
 */
public class RefurbishedConsoleModelAnimation {

	public static final AnimationDefinition FLIGHT = AnimationDefinition.Builder.withLength(6.0F).looping()
		.addAnimation("bone345", new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("Rotor", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.04F, KeyframeAnimations.posVec(0.0F, 0.2978F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08F, KeyframeAnimations.posVec(0.0F, 0.6435F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16F, KeyframeAnimations.posVec(0.0F, 1.3561F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, 1.6914F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.24F, KeyframeAnimations.posVec(0.0F, 2.005F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.28F, KeyframeAnimations.posVec(0.0F, 2.2961F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.32F, KeyframeAnimations.posVec(0.0F, 2.5654F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.36F, KeyframeAnimations.posVec(0.0F, 2.8142F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, 3.044F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, 3.2563F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.48F, KeyframeAnimations.posVec(0.0F, 3.4527F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, 3.6344F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.56F, KeyframeAnimations.posVec(0.0F, 3.8026F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, 3.9583F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.64F, KeyframeAnimations.posVec(0.0F, 4.1027F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.8F, KeyframeAnimations.posVec(0.0F, 4.5809F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 5.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.04F, KeyframeAnimations.posVec(0.0F, 5.0548F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.08F, KeyframeAnimations.posVec(0.0F, 5.0816F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.12F, KeyframeAnimations.posVec(0.0F, 5.0758F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.16F, KeyframeAnimations.posVec(0.0F, 5.0307F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.2F, KeyframeAnimations.posVec(0.0F, 4.9374F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.24F, KeyframeAnimations.posVec(0.0F, 4.7848F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.28F, KeyframeAnimations.posVec(0.0F, 4.5563F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.32F, KeyframeAnimations.posVec(0.0F, 4.228F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.36F, KeyframeAnimations.posVec(0.0F, 3.7641F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.4F, KeyframeAnimations.posVec(0.0F, 3.1125F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.44F, KeyframeAnimations.posVec(0.0F, 2.2049F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.48F, KeyframeAnimations.posVec(0.0F, 1.0098F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.52F, KeyframeAnimations.posVec(0.0F, -0.3243F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.56F, KeyframeAnimations.posVec(0.0F, -1.5127F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.6F, KeyframeAnimations.posVec(0.0F, -2.4365F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.64F, KeyframeAnimations.posVec(0.0F, -3.1296F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.68F, KeyframeAnimations.posVec(0.0F, -3.6509F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.72F, KeyframeAnimations.posVec(0.0F, -4.0454F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.76F, KeyframeAnimations.posVec(0.0F, -4.345F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.8F, KeyframeAnimations.posVec(0.0F, -4.5706F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.84F, KeyframeAnimations.posVec(0.0F, -4.7375F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.88F, KeyframeAnimations.posVec(0.0F, -4.8567F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.92F, KeyframeAnimations.posVec(0.0F, -4.9363F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.96F, KeyframeAnimations.posVec(0.0F, -4.9825F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.0F, KeyframeAnimations.posVec(0.0F, -5.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.04F, KeyframeAnimations.posVec(0.0F, -4.9992F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.08F, KeyframeAnimations.posVec(0.0F, -4.9877F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.12F, KeyframeAnimations.posVec(0.0F, -4.9648F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.16F, KeyframeAnimations.posVec(0.0F, -4.9299F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.2F, KeyframeAnimations.posVec(0.0F, -4.8826F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.24F, KeyframeAnimations.posVec(0.0F, -4.8222F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.28F, KeyframeAnimations.posVec(0.0F, -4.7479F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.32F, KeyframeAnimations.posVec(0.0F, -4.6588F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.36F, KeyframeAnimations.posVec(0.0F, -4.5543F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.4F, KeyframeAnimations.posVec(0.0F, -4.4331F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.44F, KeyframeAnimations.posVec(0.0F, -4.2944F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.48F, KeyframeAnimations.posVec(0.0F, -4.1369F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.52F, KeyframeAnimations.posVec(0.0F, -3.9593F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.56F, KeyframeAnimations.posVec(0.0F, -3.7602F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.6F, KeyframeAnimations.posVec(0.0F, -3.5381F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.64F, KeyframeAnimations.posVec(0.0F, -3.291F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.68F, KeyframeAnimations.posVec(0.0F, -3.0172F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.72F, KeyframeAnimations.posVec(0.0F, -2.7146F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.76F, KeyframeAnimations.posVec(0.0F, -2.3815F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.8F, KeyframeAnimations.posVec(0.0F, -2.0161F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.84F, KeyframeAnimations.posVec(0.0F, -1.6182F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.88F, KeyframeAnimations.posVec(0.0F, -1.1906F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.92F, KeyframeAnimations.posVec(0.0F, -0.7445F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.96F, KeyframeAnimations.posVec(0.0F, -0.3137F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.04F, KeyframeAnimations.posVec(0.0F, 0.2674F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.08F, KeyframeAnimations.posVec(0.0F, 0.6104F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.12F, KeyframeAnimations.posVec(0.0F, 0.9647F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.16F, KeyframeAnimations.posVec(0.0F, 1.3088F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.2F, KeyframeAnimations.posVec(0.0F, 1.6351F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.24F, KeyframeAnimations.posVec(0.0F, 1.9417F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.28F, KeyframeAnimations.posVec(0.0F, 2.2283F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.32F, KeyframeAnimations.posVec(0.0F, 2.4957F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.36F, KeyframeAnimations.posVec(0.0F, 2.745F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.4F, KeyframeAnimations.posVec(0.0F, 2.9772F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.44F, KeyframeAnimations.posVec(0.0F, 3.1935F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.48F, KeyframeAnimations.posVec(0.0F, 3.3949F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.52F, KeyframeAnimations.posVec(0.0F, 3.5824F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.56F, KeyframeAnimations.posVec(0.0F, 3.7569F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.6F, KeyframeAnimations.posVec(0.0F, 3.9191F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.64F, KeyframeAnimations.posVec(0.0F, 4.0698F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.68F, KeyframeAnimations.posVec(0.0F, 4.2096F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.84F, KeyframeAnimations.posVec(0.0F, 4.6716F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 5.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.04F, KeyframeAnimations.posVec(0.0F, 5.0548F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.08F, KeyframeAnimations.posVec(0.0F, 5.0816F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.12F, KeyframeAnimations.posVec(0.0F, 5.0758F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.16F, KeyframeAnimations.posVec(0.0F, 5.0307F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.2F, KeyframeAnimations.posVec(0.0F, 4.9374F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.24F, KeyframeAnimations.posVec(0.0F, 4.7848F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.28F, KeyframeAnimations.posVec(0.0F, 4.5563F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.32F, KeyframeAnimations.posVec(0.0F, 4.228F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.36F, KeyframeAnimations.posVec(0.0F, 3.7641F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.4F, KeyframeAnimations.posVec(0.0F, 3.1125F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.44F, KeyframeAnimations.posVec(0.0F, 2.2049F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.48F, KeyframeAnimations.posVec(0.0F, 1.0098F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.52F, KeyframeAnimations.posVec(0.0F, -0.3243F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.56F, KeyframeAnimations.posVec(0.0F, -1.5127F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.6F, KeyframeAnimations.posVec(0.0F, -2.4365F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.64F, KeyframeAnimations.posVec(0.0F, -3.1296F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.68F, KeyframeAnimations.posVec(0.0F, -3.6509F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.72F, KeyframeAnimations.posVec(0.0F, -4.0454F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.76F, KeyframeAnimations.posVec(0.0F, -4.345F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.8F, KeyframeAnimations.posVec(0.0F, -4.5706F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.84F, KeyframeAnimations.posVec(0.0F, -4.7375F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.88F, KeyframeAnimations.posVec(0.0F, -4.8567F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.92F, KeyframeAnimations.posVec(0.0F, -4.9363F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.96F, KeyframeAnimations.posVec(0.0F, -4.9825F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.0F, KeyframeAnimations.posVec(0.0F, -5.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.08F, KeyframeAnimations.posVec(0.0F, -4.9894F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.12F, KeyframeAnimations.posVec(0.0F, -4.9687F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.16F, KeyframeAnimations.posVec(0.0F, -4.937F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.2F, KeyframeAnimations.posVec(0.0F, -4.8939F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.24F, KeyframeAnimations.posVec(0.0F, -4.8386F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.28F, KeyframeAnimations.posVec(0.0F, -4.7705F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.32F, KeyframeAnimations.posVec(0.0F, -4.6888F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.36F, KeyframeAnimations.posVec(0.0F, -4.5927F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.4F, KeyframeAnimations.posVec(0.0F, -4.4812F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.44F, KeyframeAnimations.posVec(0.0F, -4.3533F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.48F, KeyframeAnimations.posVec(0.0F, -4.208F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.52F, KeyframeAnimations.posVec(0.0F, -4.0438F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.56F, KeyframeAnimations.posVec(0.0F, -3.8593F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.6F, KeyframeAnimations.posVec(0.0F, -3.6528F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.64F, KeyframeAnimations.posVec(0.0F, -3.4224F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.68F, KeyframeAnimations.posVec(0.0F, -3.166F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.72F, KeyframeAnimations.posVec(0.0F, -2.8811F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.76F, KeyframeAnimations.posVec(0.0F, -2.5649F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.8F, KeyframeAnimations.posVec(0.0F, -2.2145F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.84F, KeyframeAnimations.posVec(0.0F, -1.8268F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.88F, KeyframeAnimations.posVec(0.0F, -1.3997F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.92F, KeyframeAnimations.posVec(0.0F, -0.9347F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.96F, KeyframeAnimations.posVec(0.0F, -0.4461F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(6.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone125", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone132", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone140", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone142", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone144", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone135", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone137", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone139", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone146", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone148", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone150", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone352", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.25F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(0.76F, KeyframeAnimations.posVec(0.0F, 11.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.48F, KeyframeAnimations.posVec(0.0F, -1.25F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.96F, KeyframeAnimations.posVec(0.0F, -1.25F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.72F, KeyframeAnimations.posVec(0.0F, 11.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.44F, KeyframeAnimations.posVec(0.0F, -1.25F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.92F, KeyframeAnimations.posVec(0.0F, -1.25F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.76F, KeyframeAnimations.posVec(0.0F, 11.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(5.56F, KeyframeAnimations.posVec(0.0F, -2.25F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.76F, KeyframeAnimations.posVec(0.0F, -2.75F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(6.0F, KeyframeAnimations.posVec(0.0F, -2.25F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone352", new AnimationChannel(AnimationChannel.Targets.SCALE, 
			new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.76F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.48F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.96F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.72F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.44F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.76F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.48F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone358", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.posVec(4.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.0F, KeyframeAnimations.posVec(4.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.24F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.241F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(4.24F, KeyframeAnimations.posVec(4.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(6.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(6.001F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone359", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(1.0F, KeyframeAnimations.posVec(0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.0F, KeyframeAnimations.posVec(0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.001F, KeyframeAnimations.posVec(0.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.76F, KeyframeAnimations.posVec(4.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.76F, KeyframeAnimations.posVec(4.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.56F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(5.561F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(6.0F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone287", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(2.88F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone360", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.28F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.32F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.08F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.12F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.12F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.16F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.92F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.96F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.24F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.04F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone361", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.48F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.24F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.28F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.28F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.32F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.08F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.12F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.36F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.4F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.16F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.1F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone362", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.56F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.4F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.44F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.4F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.44F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.24F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.28F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.48F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.52F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.32F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.36F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone363", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.72F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.76F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.56F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.6F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.56F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.6F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.4F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.44F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.64F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.68F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.48F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.52F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone364", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.88F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.92F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.68F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.72F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.72F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.76F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.52F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.56F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.8F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.84F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.6F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.64F, KeyframeAnimations.posVec(0.0F, -0.1F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.build();

	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(6.0F).looping()
		.addAnimation("bone151", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.32F, KeyframeAnimations.degreeVec(0.0F, -7.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(2.76F, KeyframeAnimations.degreeVec(0.0F, 12.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(3.64F, KeyframeAnimations.degreeVec(0.0F, 7.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
			new Keyframe(6.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
		))
		.addAnimation("bone346", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.76F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.8F, KeyframeAnimations.degreeVec(0.0F, 1.1925F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.84F, KeyframeAnimations.degreeVec(0.0F, 3.1369F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.88F, KeyframeAnimations.degreeVec(0.0F, 5.3061F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.16F, KeyframeAnimations.degreeVec(0.0F, 21.4852F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.36F, KeyframeAnimations.degreeVec(0.0F, 32.2721F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.52F, KeyframeAnimations.degreeVec(0.0F, 39.8798F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.68F, KeyframeAnimations.degreeVec(0.0F, 46.2212F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.72F, KeyframeAnimations.degreeVec(0.0F, 47.5596F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.76F, KeyframeAnimations.degreeVec(0.0F, 48.7823F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.8F, KeyframeAnimations.degreeVec(0.0F, 49.8791F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.84F, KeyframeAnimations.degreeVec(0.0F, 50.8381F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.88F, KeyframeAnimations.degreeVec(0.0F, 51.646F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.92F, KeyframeAnimations.degreeVec(0.0F, 52.2869F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.96F, KeyframeAnimations.degreeVec(0.0F, 52.7425F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.0F, KeyframeAnimations.degreeVec(0.0F, 52.9881F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.04F, KeyframeAnimations.degreeVec(0.0F, 53.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 53.0504F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.24F, KeyframeAnimations.degreeVec(0.0F, 53.279F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.28F, KeyframeAnimations.degreeVec(0.0F, 53.6213F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.32F, KeyframeAnimations.degreeVec(0.0F, 54.0835F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.52F, KeyframeAnimations.degreeVec(0.0F, 57.2967F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.72F, KeyframeAnimations.degreeVec(0.0F, 59.4329F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.24F, KeyframeAnimations.degreeVec(0.0F, 60.2778F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.36F, KeyframeAnimations.degreeVec(0.0F, 60.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.52F, KeyframeAnimations.degreeVec(0.0F, 59.0022F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.68F, KeyframeAnimations.degreeVec(0.0F, 56.77F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.8F, KeyframeAnimations.degreeVec(0.0F, 54.1548F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.84F, KeyframeAnimations.degreeVec(0.0F, 53.0834F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.88F, KeyframeAnimations.degreeVec(0.0F, 51.906F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.92F, KeyframeAnimations.degreeVec(0.0F, 50.6168F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.96F, KeyframeAnimations.degreeVec(0.0F, 49.2136F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 47.6926F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.04F, KeyframeAnimations.degreeVec(0.0F, 46.0501F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.08F, KeyframeAnimations.degreeVec(0.0F, 44.2829F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.12F, KeyframeAnimations.degreeVec(0.0F, 42.3912F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.16F, KeyframeAnimations.degreeVec(0.0F, 40.3719F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.2F, KeyframeAnimations.degreeVec(0.0F, 38.2279F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.24F, KeyframeAnimations.degreeVec(0.0F, 35.9621F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.28F, KeyframeAnimations.degreeVec(0.0F, 33.5808F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.52F, KeyframeAnimations.degreeVec(0.0F, 17.7354F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.6F, KeyframeAnimations.degreeVec(0.0F, 12.5428F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.64F, KeyframeAnimations.degreeVec(0.0F, 10.1405F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.68F, KeyframeAnimations.degreeVec(0.0F, 7.9226F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.72F, KeyframeAnimations.degreeVec(0.0F, 5.9274F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.76F, KeyframeAnimations.degreeVec(0.0F, 4.1847F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.8F, KeyframeAnimations.degreeVec(0.0F, 2.7165F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.84F, KeyframeAnimations.degreeVec(0.0F, 1.5379F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.88F, KeyframeAnimations.degreeVec(0.0F, 0.6554F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.92F, KeyframeAnimations.degreeVec(0.0F, 0.069F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.96F, KeyframeAnimations.degreeVec(0.0F, -0.2285F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.0F, KeyframeAnimations.degreeVec(0.0F, -0.2472F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.04F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone346", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.76F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.28F, KeyframeAnimations.posVec(0.0F, 0.2127F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.8F, KeyframeAnimations.posVec(0.0F, -0.2667F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.12F, KeyframeAnimations.posVec(0.0F, -0.4679F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.28F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.44F, KeyframeAnimations.posVec(0.0F, -0.4577F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.48F, KeyframeAnimations.posVec(0.0F, -0.4258F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.52F, KeyframeAnimations.posVec(0.0F, -0.3762F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.56F, KeyframeAnimations.posVec(0.0F, -0.2968F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.64F, KeyframeAnimations.posVec(0.0F, -0.0605F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.68F, KeyframeAnimations.posVec(0.0F, 0.007F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.72F, KeyframeAnimations.posVec(0.0F, 0.0424F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.76F, KeyframeAnimations.posVec(0.0F, 0.0598F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.04F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone348", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.8F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.84F, KeyframeAnimations.degreeVec(0.0F, 0.7691F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.36F, KeyframeAnimations.degreeVec(0.0F, 17.4003F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.88F, KeyframeAnimations.degreeVec(0.0F, 33.7542F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.24F, KeyframeAnimations.degreeVec(0.0F, 43.7688F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.48F, KeyframeAnimations.degreeVec(0.0F, 49.2736F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.64F, KeyframeAnimations.degreeVec(0.0F, 51.9646F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.68F, KeyframeAnimations.degreeVec(0.0F, 52.4351F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.72F, KeyframeAnimations.degreeVec(0.0F, 52.7886F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.76F, KeyframeAnimations.degreeVec(0.0F, 52.9932F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.8F, KeyframeAnimations.degreeVec(0.0F, 53.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.96F, KeyframeAnimations.degreeVec(0.0F, 53.0504F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.0F, KeyframeAnimations.degreeVec(0.0F, 53.279F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.04F, KeyframeAnimations.degreeVec(0.0F, 53.6213F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.08F, KeyframeAnimations.degreeVec(0.0F, 54.0835F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.28F, KeyframeAnimations.degreeVec(0.0F, 57.2967F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.48F, KeyframeAnimations.degreeVec(0.0F, 59.4329F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 60.2778F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.12F, KeyframeAnimations.degreeVec(0.0F, 60.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.28F, KeyframeAnimations.degreeVec(0.0F, 59.0022F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.44F, KeyframeAnimations.degreeVec(0.0F, 56.77F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.56F, KeyframeAnimations.degreeVec(0.0F, 54.1548F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.6F, KeyframeAnimations.degreeVec(0.0F, 53.0834F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.64F, KeyframeAnimations.degreeVec(0.0F, 51.906F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.68F, KeyframeAnimations.degreeVec(0.0F, 50.6168F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.72F, KeyframeAnimations.degreeVec(0.0F, 49.2136F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.76F, KeyframeAnimations.degreeVec(0.0F, 47.6926F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.8F, KeyframeAnimations.degreeVec(0.0F, 46.0501F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.84F, KeyframeAnimations.degreeVec(0.0F, 44.2829F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.88F, KeyframeAnimations.degreeVec(0.0F, 42.3912F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.92F, KeyframeAnimations.degreeVec(0.0F, 40.3719F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.96F, KeyframeAnimations.degreeVec(0.0F, 38.2279F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.0F, KeyframeAnimations.degreeVec(0.0F, 35.9621F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.04F, KeyframeAnimations.degreeVec(0.0F, 33.5808F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.28F, KeyframeAnimations.degreeVec(0.0F, 17.7354F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.36F, KeyframeAnimations.degreeVec(0.0F, 12.5428F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.4F, KeyframeAnimations.degreeVec(0.0F, 10.1405F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.44F, KeyframeAnimations.degreeVec(0.0F, 7.9226F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.48F, KeyframeAnimations.degreeVec(0.0F, 5.9274F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.52F, KeyframeAnimations.degreeVec(0.0F, 4.1847F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.56F, KeyframeAnimations.degreeVec(0.0F, 2.7165F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.6F, KeyframeAnimations.degreeVec(0.0F, 1.5379F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.64F, KeyframeAnimations.degreeVec(0.0F, 0.6554F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.68F, KeyframeAnimations.degreeVec(0.0F, 0.069F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.72F, KeyframeAnimations.degreeVec(0.0F, -0.2285F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.76F, KeyframeAnimations.degreeVec(0.0F, -0.2472F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.8F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone348", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.24F, KeyframeAnimations.posVec(0.0F, -0.0726F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, -0.0296F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, 0.0069F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.48F, KeyframeAnimations.posVec(0.0F, 0.0606F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, 0.1343F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, 0.3063F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.64F, KeyframeAnimations.posVec(0.0F, 0.3744F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.68F, KeyframeAnimations.posVec(0.0F, 0.4245F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.72F, KeyframeAnimations.posVec(0.0F, 0.46F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.8F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.32F, KeyframeAnimations.posVec(0.0F, 0.3411F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.84F, KeyframeAnimations.posVec(0.0F, 0.0517F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.36F, KeyframeAnimations.posVec(0.0F, -0.2431F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.88F, KeyframeAnimations.posVec(0.0F, -0.4744F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.04F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.2F, KeyframeAnimations.posVec(0.0F, -0.4577F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.24F, KeyframeAnimations.posVec(0.0F, -0.4258F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.28F, KeyframeAnimations.posVec(0.0F, -0.3762F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.32F, KeyframeAnimations.posVec(0.0F, -0.2968F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.4F, KeyframeAnimations.posVec(0.0F, -0.0605F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.44F, KeyframeAnimations.posVec(0.0F, 0.007F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.48F, KeyframeAnimations.posVec(0.0F, 0.0424F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.52F, KeyframeAnimations.posVec(0.0F, 0.0598F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.8F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone349", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16F, KeyframeAnimations.degreeVec(0.0F, -0.1757F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.36F, KeyframeAnimations.degreeVec(0.0F, -2.0988F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.72F, KeyframeAnimations.degreeVec(0.0F, -8.5463F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.24F, KeyframeAnimations.degreeVec(0.0F, -21.3374F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.76F, KeyframeAnimations.degreeVec(0.0F, -35.3062F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.24F, KeyframeAnimations.degreeVec(0.0F, -47.2309F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.56F, KeyframeAnimations.degreeVec(0.0F, -53.751F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.84F, KeyframeAnimations.degreeVec(0.0F, -57.9147F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.04F, KeyframeAnimations.degreeVec(0.0F, -59.6611F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.12F, KeyframeAnimations.degreeVec(0.0F, -60.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.28F, KeyframeAnimations.degreeVec(0.0F, -59.701F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, -59.3855F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.36F, KeyframeAnimations.degreeVec(0.0F, -58.97F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.4F, KeyframeAnimations.degreeVec(0.0F, -58.4534F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.44F, KeyframeAnimations.degreeVec(0.0F, -57.8346F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.48F, KeyframeAnimations.degreeVec(0.0F, -57.1126F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.52F, KeyframeAnimations.degreeVec(0.0F, -56.286F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.56F, KeyframeAnimations.degreeVec(0.0F, -55.356F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.6F, KeyframeAnimations.degreeVec(0.0F, -54.3236F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.64F, KeyframeAnimations.degreeVec(0.0F, -53.1903F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.8F, KeyframeAnimations.degreeVec(0.0F, -47.6858F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.28F, KeyframeAnimations.degreeVec(0.0F, -25.1688F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.48F, KeyframeAnimations.degreeVec(0.0F, -15.7824F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.64F, KeyframeAnimations.degreeVec(0.0F, -9.3384F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.8F, KeyframeAnimations.degreeVec(0.0F, -4.1567F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.96F, KeyframeAnimations.degreeVec(0.0F, -0.3476F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.12F, KeyframeAnimations.degreeVec(0.0F, 2.0949F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.28F, KeyframeAnimations.degreeVec(0.0F, 3.2436F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.44F, KeyframeAnimations.degreeVec(0.0F, 3.2038F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.64F, KeyframeAnimations.degreeVec(0.0F, 1.6511F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.76F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone349", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, 0.2059F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.04F, KeyframeAnimations.posVec(0.0F, 0.4291F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.24F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.76F, KeyframeAnimations.posVec(0.0F, 0.2638F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.28F, KeyframeAnimations.posVec(0.0F, -0.1502F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.72F, KeyframeAnimations.posVec(0.0F, -0.4373F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.96F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.16F, KeyframeAnimations.posVec(0.0F, -0.4449F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.48F, KeyframeAnimations.posVec(0.0F, -0.1034F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.68F, KeyframeAnimations.posVec(0.0F, 0.048F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.04F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.56F, KeyframeAnimations.posVec(0.0F, -0.1421F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.08F, KeyframeAnimations.posVec(0.0F, -0.1491F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.6F, KeyframeAnimations.posVec(0.0F, -0.0721F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.88F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone351", new AnimationChannel(AnimationChannel.Targets.ROTATION, 
			new Keyframe(0.72F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.76F, KeyframeAnimations.degreeVec(0.0F, -0.3713F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.28F, KeyframeAnimations.degreeVec(0.0F, -8.1244F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.8F, KeyframeAnimations.degreeVec(0.0F, -15.5848F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.32F, KeyframeAnimations.degreeVec(0.0F, -22.1175F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.84F, KeyframeAnimations.degreeVec(0.0F, -27.2567F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.28F, KeyframeAnimations.degreeVec(0.0F, -29.8766F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.32F, KeyframeAnimations.degreeVec(0.0F, -30.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.6F, KeyframeAnimations.degreeVec(0.0F, -29.955F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.8F, KeyframeAnimations.degreeVec(0.0F, -28.7057F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, -26.1284F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.16F, KeyframeAnimations.degreeVec(0.0F, -22.8973F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.36F, KeyframeAnimations.degreeVec(0.0F, -17.2705F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.6F, KeyframeAnimations.degreeVec(0.0F, -9.0777F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.76F, KeyframeAnimations.degreeVec(0.0F, -4.2377F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.8F, KeyframeAnimations.degreeVec(0.0F, -3.2541F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.84F, KeyframeAnimations.degreeVec(0.0F, -2.3795F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.88F, KeyframeAnimations.degreeVec(0.0F, -1.6173F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.92F, KeyframeAnimations.degreeVec(0.0F, -0.9678F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.96F, KeyframeAnimations.degreeVec(0.0F, -0.4297F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.addAnimation("bone351", new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, 0.4729F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.04F, KeyframeAnimations.posVec(0.0F, 0.3829F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.56F, KeyframeAnimations.posVec(0.0F, 0.28F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.08F, KeyframeAnimations.posVec(0.0F, 0.1741F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(2.6F, KeyframeAnimations.posVec(0.0F, 0.0732F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.12F, KeyframeAnimations.posVec(0.0F, 0.0007F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.16F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.36F, KeyframeAnimations.posVec(0.0F, 0.0278F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.52F, KeyframeAnimations.posVec(0.0F, 0.1278F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.56F, KeyframeAnimations.posVec(0.0F, 0.1329F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(3.92F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.44F, KeyframeAnimations.posVec(0.0F, -0.0605F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(4.96F, KeyframeAnimations.posVec(0.0F, 0.0904F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.48F, KeyframeAnimations.posVec(0.0F, 0.3354F, 0.0F), AnimationChannel.Interpolations.LINEAR),
			new Keyframe(5.84F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.LINEAR)
		))
		.build();
}