plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = rootProject.neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer_common.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = "${rootProject.parchment_minecraft_version}"
        mappingsVersion = "${rootProject.parchment_version}"
    }
}


dependencies {

    compileOnly group: 'org.spongepowered', name: 'mixin', version: rootProject.mixin_version

    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${rootProject.mixin_extras_version}"))

    // Forge Config API Port
//    compileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${rootProject.forge_config_api_port_version}"

    //Cloth Config common module
//    modCompileOnlyApi("me.shedaniel.cloth:cloth-config:${rootProject.cloth_config_version}")

//    include "me.shedaniel.cloth:cloth-config:${rootProject.cloth_config_version}"

    // Sodium
//    modImplementation "maven.modrinth:sodium:${rootProject.sodium_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}